# Generated by Django 5.1.5 on 2025-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
