# Generated by Django 5.1.5 on 2025-01-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savsh', '0002_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, default='No description', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
